### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by cofuente**
Creating a draft PR to help give my notes on code standards.

### CODE REVIEW

**Comment by cofuente** [comment]
Hello everyone, 

I am making this draft PR to be able to have a space everyone can access, comment, discuss, ask questions, etc, as I give my first review. 

- [ ] As referenced in issue #17 we absolutely need to establish a good linter AND code formatter.
- [ ] NPM audits and fixes should be conducted regularly before pushing up new code. As of today running the audit shows the main branch has 11 vulnerabilities (3 low, 8 high).
- [ ] With the previous point in mind, the main branch will require a refactor to step away from the create-react-app paradigm and be able to change dependencies without larger breaking changes.
- [ ] There are a lot of redundant files that seem to serve no purpose. Those should be deleted. I you ever need them again, they will be accessible via the repo's commit history (which is properly conserved when we use version control best practices).
- [ ] Similarly, all commented code should be deleted. The only comments allowed should be for enhanced signage in code readability.
- [ ] Also need to prune unused and stale branches on the repo. You may keep them locally if you wish but we want to make each repo as clean and easy to navigate as possible.

**Comment by Nfratt** [comment]
Been reviewing these should I comment one by one or as a whole?

**Comment by Nfratt** [comment]
Ran audit fixes the breaking issue had to do with eslint not being set up properly.
We should enforce self closing tags if the tag has no child  in our Linter.
Thanks for removing the old favicon.
The margin top can be removed.
About us was left commented out in case we needed it again for any issues in the aboutus.jsx component. It can probably be removed now.
The Apple-touch-icon was auto generated. I believe it can be removed. 
The form doesn't work when in source. Should make a ticket to investigate why. 
The Assest’s folder in src was used early on. I don't believe it's still in use. So it can most likely be deleted. 
Should we not keep the test file in incase we want to run tests?

**Comment by alcastonguay** [comment]
There is a ticket for the form issue and I have added notes about my research for this. Are there any security issues with this though? I couldn't find anything that made it an urgent issue. 

I think in additional to a linter we should establish some basic guidelines around code cleanliness, such as no commented out code in main/development, and adding some basic comment requirements. 

Do we know how the test file works? We should look into setting up some sort of testing framework.

**Pull request closed without merging**
