### PR TITLE
Prep and Homepage Redesign

### PR DESCRIPTION
**Pull request by alcastonguay**
- Updated PrEP page to use Bootstrap
- Update Homepage to new design
  - Added background image
  - Added people images
- Additional CSS updates as needed

### CODE REVIEW

**Comment by alcastonguay** [comment]
@Nfratt I did what I could if you would like to take it from here for any additional cleanup!

**Comment by Nfratt** [comment]
looking this over so far it looks GREAT! you did amazing! There are some things that need clean up but its just updating stuff that wasn't touched

**Comment by alcastonguay** [comment]
@Nfratt Did some more updates, I updated the mail page so it uses the same stylesheet as the rest of the site. We still need to do the dark mode fixes, but that's it. If this is good to go, we can merge this and start a new branch for the dark mode fixes.

**Comment by Nfratt** [comment]
wow Looks Great! I agree on the Dark mode fixes. Additionally Ill look into seeing if we can get dark mode on the mailing list page

**Review by Nfratt — APPROVED** [review]
Looks great after some testing everything is working. still have some minor styling things to fix but we can certainly merge this into dev

**Pull request merged**
