### PR TITLE
Development to main 

### PR DESCRIPTION
**Pull request by Nfratt**

### CODE REVIEW

**Comment by Nfratt** [comment]
This is a quick resolve just wanted to get this up before I added the new nav stuff

**Comment by alcastonguay** [comment]
Is Jill's picture supposed to be square like the rest of them? It's still showing as portrait shaped for me.

**Comment by Nfratt** [comment]
> Is Jill's picture supposed to be square like the rest of them? It's still showing as portrait shaped for me.

It should not. It should be fixed in the latest revision if not well have to escalate the fix.

**Comment by Nfratt** [comment]
> 
It should be square. it keeps resetting to be elongated

**Review by alcastonguay — APPROVED** [review]

**Comment by Nfratt** [comment]
Yes It should be corrected on the latest version we just pulled into dev.

**Pull request merged**
