### PR TITLE
Create Header component, create Sex Toy page.

### PR DESCRIPTION
**Pull request by alcastonguay**

### CODE REVIEW

**Comment by Nfratt** [comment]
the text color while using dark mode should be darker you cant read it with the current background color

**Comment by alcastonguay** [comment]
> 
> 
> Looks good tested and works just needs images then can go in to dev

Do we need images to merge? It would be nice to get the header component into the dev branch.

**Comment by Nfratt** [comment]
Looks good there was the one issue where Heading was input as heading. should be all fixed

**Review by Nfratt — APPROVED** [review]
Looks Great there was the one issue where Heading was input as heading. should be all fixed

**Pull request merged**
